
> ethse@0.0.1 test C:\D\programming\projects\Solidity\ethe
> truffle test

Using network 'development'.



  Contract: Credits
    √ should allow to ask for credits (113ms)
    √ should fail on overflow while crediting
    1) should emit event after credit request
    > No events were emitted
{ logIndex: 0,
  transactionIndex: 0,
  transactionHash: '0x45ca2264f04527dc27b8d87bdf012902a1e675a00c1efc465ee8fa0fae1033a7',
  blockHash: '0xbc5dcacdc10405ff29627c7fdeadeff46a9c7fba60379c8fd13ce2bcbed34ab6',
  blockNumber: 15,
  address: '0xf15d2a7aaf028acd271bd2ba0f317e9380862127',
  type: 'mined',
  event: 'CreditRequested',
  args:
   { requestor: '0x38a89042d5b82639284b55a8900e7d0dcda66500',
     amount: { [String: '1000'] s: 1, e: 3, c: [Array] } } }
    √ should deny zero credit request
    √ should deny zero credit request (119ms)
    √ should not allow owner to request credits (49ms)
    2) owner can approve credit request
    3) "after each" hook: after test for "owner can approve credit request"


  5 passing (568ms)
  3 failing

  1) Contract: Credits should emit event after credit request:
     Uncaught AssertionError: assert.fail()
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

  2) Contract: Credits owner can approve credit request:
     Error: LevelUpArrayAdapter named 'blockLogs' index out of range: index 15; length: 15
    at C:\D\programming\projects\Solidity\ethe\node_modules\ethereumjs-testrpc\build\cli.node.js:79701:23
    at C:\D\programming\projects\Solidity\ethe\node_modules\ethereumjs-testrpc\build\cli.node.js:79675:5
    at C:\D\programming\projects\Solidity\ethe\node_modules\ethereumjs-testrpc\build\cli.node.js:80121:12
    at C:\D\programming\projects\Solidity\ethe\node_modules\ethereumjs-testrpc\build\cli.node.js:79886:19
    at C:\D\programming\projects\Solidity\ethe\node_modules\ethereumjs-testrpc\build\cli.node.js:82025:7
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  Error: Error: LevelUpArrayAdapter named 'blockLogs' index out of range: index 15; length: 15
      at node_modules\ethereumjs-testrpc\build\cli.node.js:79701:23
      at node_modules\ethereumjs-testrpc\build\cli.node.js:79675:5
      at node_modules\ethereumjs-testrpc\build\cli.node.js:80121:12
      at node_modules\ethereumjs-testrpc\build\cli.node.js:79886:19
      at node_modules\ethereumjs-testrpc\build\cli.node.js:82025:7
      at _combinedTickCallback (internal/process/next_tick.js:95:7)
      at process._tickCallback (internal/process/next_tick.js:161:9)
      at Object.InvalidResponse (node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1)
      at node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
      at node_modules\truffle\build\webpack:\~\truffle-provider\wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
      at IncomingMessage.<anonymous> (node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickCallback (internal/process/next_tick.js:161:9)

  3) Contract: Credits "after each" hook: after test for "owner can approve credit request":
     RPC Error: Error: LevelUpArrayAdapter named 'blockLogs' index out of range: index 15; length: 15
    at C:\D\programming\projects\Solidity\ethe\node_modules\ethereumjs-testrpc\build\cli.node.js:79701:23
    at C:\D\programming\projects\Solidity\ethe\node_modules\ethereumjs-testrpc\build\cli.node.js:79675:5
    at C:\D\programming\projects\Solidity\ethe\node_modules\ethereumjs-testrpc\build\cli.node.js:80121:12
    at C:\D\programming\projects\Solidity\ethe\node_modules\ethereumjs-testrpc\build\cli.node.js:79886:19
    at C:\D\programming\projects\Solidity\ethe\node_modules\ethereumjs-testrpc\build\cli.node.js:82025:7
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  Error: RPC Error: Error: LevelUpArrayAdapter named 'blockLogs' index out of range: index 15; length: 15
      at node_modules\ethereumjs-testrpc\build\cli.node.js:79701:23
      at node_modules\ethereumjs-testrpc\build\cli.node.js:79675:5
      at node_modules\ethereumjs-testrpc\build\cli.node.js:80121:12
      at node_modules\ethereumjs-testrpc\build\cli.node.js:79886:19
      at node_modules\ethereumjs-testrpc\build\cli.node.js:82025:7
      at _combinedTickCallback (internal/process/next_tick.js:95:7)
      at process._tickCallback (internal/process/next_tick.js:161:9)
      at intermediary (node_modules\truffle\build\webpack:\~\truffle-core\lib\testing\testrunner.js:230:1)
      at node_modules\truffle\build\webpack:\~\truffle-provider\wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
      at IncomingMessage.<anonymous> (node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickCallback (internal/process/next_tick.js:161:9)



npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! ethse@0.0.1 test: `truffle test`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the ethse@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\igor\AppData\Roaming\npm-cache\_logs\2018-03-11T08_25_10_661Z-debug.log
